name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0"]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install gems
        run: |
          gem install bundler -v 2.2.15
          bundle install
      - name: Run the specs task
        env:
          COVERAGE: "true"
        run: |
          bundle exec rake spec
